export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    GALLERY: '/gallery',
    DISCUSSIONS: '/discussions',
    MENU: '/menu',
    CONTACT: '/contact',
    WATER: '/water',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    ORDERS: '/admin/orders',
    NEW_ORDER: '/admin/orders/new',
    CUSTOMERS: '/admin/customers',
    CUSTOMER_DETAILS: '/admin/customers/:id',
    MENU: '/admin/menu',
    ANALYTICS: '/admin/analytics',
    GALLERY: '/admin/gallery',
    DISCUSSIONS: '/admin/discussions',
    PRINTER: '/admin/printer',
    SETTINGS: '/admin/settings',
    WATER: {
      DASHBOARD: '/admin/water',
      ORDERS: '/admin/water/orders',
      NEW_ORDER: '/admin/water/orders/new',
      PRODUCTS: '/admin/water/products',
      CUSTOMERS: '/admin/water/customers',
      CUSTOMER_DETAILS: '/admin/water/customers/:id',
      PAYMENTS: '/admin/water/payments',
      EVENTS: '/admin/water/events',
      ANALYTICS: '/admin/water/analytics',
    },
  },
} as const;
